export { useGetPartnerships }   from "./useGetPartnerships";
export { useGetInactivePartnerships } from "./useGetInactivePartnerships";
export { useGetPartnership }    from "./useGetPartnership";
export { useCreatePartnership } from "./useCreatePartnership";
export { useUpdatePartnership } from "./useUpdatePartnership";
export { useDeletePartnership } from "./useDeletePartnership";
export { useRestorePartnership } from "./useRestorePartnership";
export { usePartnershipList }   from "./usePartnershipList";
export { useInactivePartnershipList } from "./useInactivePartnershipList";
