export const COUNTRIES = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Taiwan", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const NATIONALITIES = [
  { name: "Afghan", label: "Afghan" },
  { name: "Albanian", label: "Albanian" },
  { name: "Algerian", label: "Algerian" },
  { name: "Andorran", label: "Andorran" },
  { name: "Angolan", label: "Angolan" },
  { name: "Antiguan and Barbudan", label: "Antiguan and Barbudan" },
  { name: "Argentine", label: "Argentine" },
  { name: "Armenian", label: "Armenian" },
  { name: "Australian", label: "Australian" },
  { name: "Austrian", label: "Austrian" },
  { name: "Azerbaijani", label: "Azerbaijani" },
  { name: "Bahamian", label: "Bahamian" },
  { name: "Bahraini", label: "Bahraini" },
  { name: "Bangladeshi", label: "Bangladeshi" },
  { name: "Barbadian", label: "Barbadian" },
  { name: "Belarusian", label: "Belarusian" },
  { name: "Belgian", label: "Belgian" },
  { name: "Belizean", label: "Belizean" },
  { name: "Beninese", label: "Beninese" },
  { name: "Bhutanese", label: "Bhutanese" },
  { name: "Bolivian", label: "Bolivian" },
  { name: "Bosnian and Herzegovinian", label: "Bosnian and Herzegovinian" },
  { name: "Botswanan", label: "Botswanan" },
  { name: "Brazilian", label: "Brazilian" },
  { name: "Bruneian", label: "Bruneian" },
  { name: "Bulgarian", label: "Bulgarian" },
  { name: "Burkinabe", label: "Burkinabe" },
  { name: "Burundian", label: "Burundian" },
  { name: "Cambodian", label: "Cambodian" },
  { name: "Cameroonian", label: "Cameroonian" },
  { name: "Canadian", label: "Canadian" },
  { name: "Cape Verdean", label: "Cape Verdean" },
  { name: "Central African", label: "Central African" },
  { name: "Chadian", label: "Chadian" },
  { name: "Chilean", label: "Chilean" },
  { name: "Chinese", label: "Chinese" },
  { name: "Colombian", label: "Colombian" },
  { name: "Comoran", label: "Comoran" },
  { name: "Costa Rican", label: "Costa Rican" },
  { name: "Croatian", label: "Croatian" },
  { name: "Cuban", label: "Cuban" },
  { name: "Cypriot", label: "Cypriot" },
  { name: "Czech", label: "Czech" },
  { name: "Danish", label: "Danish" },
  { name: "Djiboutian", label: "Djiboutian" },
  { name: "Dominican", label: "Dominican" },
  { name: "Ecuadorian", label: "Ecuadorian" },
  { name: "Egyptian", label: "Egyptian" },
  { name: "Salvadoran", label: "Salvadoran" },
  { name: "Equatorial Guinean", label: "Equatorial Guinean" },
  { name: "Eritrean", label: "Eritrean" },
  { name: "Estonian", label: "Estonian" },
  { name: "Eswatini", label: "Eswatini" },
  { name: "Ethiopian", label: "Ethiopian" },
  { name: "Fijian", label: "Fijian" },
  { name: "Finnish", label: "Finnish" },
  { name: "French", label: "French" },
  { name: "Gabonese", label: "Gabonese" },
  { name: "Gambian", label: "Gambian" },
  { name: "Georgian", label: "Georgian" },
  { name: "German", label: "German" },
  { name: "Ghanaian", label: "Ghanaian" },
  { name: "Greek", label: "Greek" },
  { name: "Grenadian", label: "Grenadian" },
  { name: "Guatemalan", label: "Guatemalan" },
  { name: "Guinean", label: "Guinean" },
  { name: "Guinea-Bissauan", label: "Guinea-Bissauan" },
  { name: "Guyanese", label: "Guyanese" },
  { name: "Haitian", label: "Haitian" },
  { name: "Honduran", label: "Honduran" },
  { name: "Hungarian", label: "Hungarian" },
  { name: "Icelandic", label: "Icelandic" },
  { name: "Indian", label: "Indian" },
  { name: "Indonesian", label: "Indonesian" },
  { name: "Iranian", label: "Iranian" },
  { name: "Iraqi", label: "Iraqi" },
  { name: "Irish", label: "Irish" },
  { name: "Italian", label: "Italian" },
  { name: "Jamaican", label: "Jamaican" },
  { name: "Japanese", label: "Japanese" },
  { name: "Jordanian", label: "Jordanian" },
  { name: "Kazakhstani", label: "Kazakhstani" },
  { name: "Kenyan", label: "Kenyan" },
  { name: "Kiribati", label: "Kiribati" },
  { name: "Kuwaiti", label: "Kuwaiti" },
  { name: "Kyrgyzstani", label: "Kyrgyzstani" },
  { name: "Lao", label: "Lao" },
  { name: "Latvian", label: "Latvian" },
  { name: "Lebanese", label: "Lebanese" },
  { name: "Basotho", label: "Basotho" },
  { name: "Liberian", label: "Liberian" },
  { name: "Libyan", label: "Libyan" },
  { name: "Liechtensteinian", label: "Liechtensteinian" },
  { name: "Lithuanian", label: "Lithuanian" },
  { name: "Luxembourgish", label: "Luxembourgish" },
  { name: "Malagasy", label: "Malagasy" },
  { name: "Malawian", label: "Malawian" },
  { name: "Malaysian", label: "Malaysian" },
  { name: "Maldivian", label: "Maldivian" },
  { name: "Malian", label: "Malian" },
  { name: "Maltese", label: "Maltese" },
  { name: "Marshallese", label: "Marshallese" },
  { name: "Mauritanian", label: "Mauritanian" },
  { name: "Mauritian", label: "Mauritian" },
  { name: "Mexican", label: "Mexican" },
  { name: "Micronesian", label: "Micronesian" },
  { name: "Moldovan", label: "Moldovan" },
  { name: "Monacan", label: "Monacan" },
  { name: "Mongolian", label: "Mongolian" },
  { name: "Montenegrin", label: "Montenegrin" },
  { name: "Moroccan", label: "Moroccan" },
  { name: "Mozambican", label: "Mozambican" },
  { name: "Myanmarian", label: "Myanmarian" },
  { name: "Namibian", label: "Namibian" },
  { name: "Nauruan", label: "Nauruan" },
  { name: "Nepalese", label: "Nepalese" },
  { name: "Dutch", label: "Dutch" },
  { name: "New Zealander", label: "New Zealander" },
  { name: "Nicaraguan", label: "Nicaraguan" },
  { name: "Nigerien", label: "Nigerien" },
  { name: "Nigerian", label: "Nigerian" },
  { name: "North Korean", label: "North Korean" },
  { name: "Macedonian", label: "Macedonian" },
  { name: "Norwegian", label: "Norwegian" },
  { name: "Omani", label: "Omani" },
  { name: "Pakistani", label: "Pakistani" },
  { name: "Palauan", label: "Palauan" },
  { name: "Palestinian", label: "Palestinian" },
  { name: "Panamanian", label: "Panamanian" },
  { name: "Papua New Guinean", label: "Papua New Guinean" },
  { name: "Paraguayan", label: "Paraguayan" },
  { name: "Peruvian", label: "Peruvian" },
  { name: "Filipino", label: "Filipino" },
  { name: "Polish", label: "Polish" },
  { name: "Portuguese", label: "Portuguese" },
  { name: "Qatari", label: "Qatari" },
  { name: "Romanian", label: "Romanian" },
  { name: "Russian", label: "Russian" },
  { name: "Rwandan", label: "Rwandan" },
  { name: "Saudi", label: "Saudi" },
  { name: "Senegalese", label: "Senegalese" },
  { name: "Serbian", label: "Serbian" },
  { name: "Singaporean", label: "Singaporean" },
  { name: "Slovak", label: "Slovak" },
  { name: "Slovenian", label: "Slovenian" },
  { name: "Somali", label: "Somali" },
  { name: "South African", label: "South African" },
  { name: "South Korean", label: "South Korean" },
  { name: "Spanish", label: "Spanish" },
  { name: "Sri Lankan", label: "Sri Lankan" },
  { name: "Sudanese", label: "Sudanese" },
  { name: "Surinamese", label: "Surinamese" },
  { name: "Swedish", label: "Swedish" },
  { name: "Swiss", label: "Swiss" },
  { name: "Syrian", label: "Syrian" },
  { name: "Taiwanese", label: "Taiwanese" },
  { name: "Tajikistani", label: "Tajikistani" },
  { name: "Tanzanian", label: "Tanzanian" },
  { name: "Thai", label: "Thai" },
  { name: "Togolese", label: "Togolese" },
  { name: "Trinidadian and Tobagonian", label: "Trinidadian and Tobagonian" },
  { name: "Tunisian", label: "Tunisian" },
  { name: "Turkish", label: "Turkish" },
  { name: "Turkmen", label: "Turkmen" },
  { name: "Ugandan", label: "Ugandan" },
  { name: "Ukrainian", label: "Ukrainian" },
  { name: "Emirati", label: "Emirati" },
  { name: "British", label: "British" },
  { name: "American", label: "American" },
  { name: "Uruguayan", label: "Uruguayan" },
  { name: "Uzbekistani", label: "Uzbekistani" },
  { name: "Vanuatuan", label: "Vanuatuan" },
  { name: "Vatican", label: "Vatican" },
  { name: "Venezuelan", label: "Venezuelan" },
  { name: "Vietnamese", label: "Vietnamese" },
  { name: "Yemeni", label: "Yemeni" },
  { name: "Zambian", label: "Zambian" },
  { name: "Zimbabwean", label: "Zimbabwean" }
];
